on:
  push:
    tags:        
      - v0.0.0
  workflow_dispatch:
name: Create a list of issues
permissions:
  contents: read
  issues: write 
jobs:
  create:
    runs-on: ubuntu-latest
    uses: macroscian/macroscian-issue-workflow/.github/workflows/setup-issues.yml@main
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      json: .github/issues.json
    steps:
      - uses: actions/checkout@v2
