on:
  push:
    tags:        
      - v0.0.0
  workflow_dispatch:
name: Create a list of issues
permissions:
  contents: read
  issues: write 
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: macroscian/create-issues@v2.6.20
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          json: .github/issues.json
