on:
  push:
    tags:        
      - v0.0.0
  workflow_dispatch:
name: Create a list of issues
permissions:
  contents: read
  issues: write 
jobs:
  create:
    uses: macroscian/macroscian-issue-workflow/.github/workflows/setup-issues.yml@main
    with:
      json: .github/issues.json
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
